import { readFile } from "node:fs/promises";

const files = {
  main: await readFile(new URL("../src/main.js", import.meta.url), "utf8"),
  portal: await readFile(new URL("../src/portal.js", import.meta.url), "utf8"),
  exerciseCatalog: await readFile(new URL("../src/exercise-catalog.js", import.meta.url), "utf8"),
  pose: await readFile(new URL("../src/pose.js", import.meta.url), "utf8"),
  movementProfiles: await readFile(new URL("../src/movement-profiles.js", import.meta.url), "utf8"),
  movementGame: await readFile(new URL("../src/movement-game.js", import.meta.url), "utf8"),
  css: await readFile(new URL("../src/styles.css", import.meta.url), "utf8"),
  demo: await readFile(new URL("../DEMO.md", import.meta.url), "utf8"),
  schema: await readFile(new URL("../supabase/schema.sql", import.meta.url), "utf8"),
  securityMigration: await readFile(new URL("../supabase/migrations/20260825_secure_connections.sql", import.meta.url), "utf8"),
  personalizationMigration: await readFile(new URL("../supabase/migrations/202608250001_patient_personalization.sql", import.meta.url), "utf8"),
  productionSecurityMigration: await readFile(new URL("../supabase/migrations/202608250004_production_security.sql", import.meta.url), "utf8"),
  onboardingGrantMigration: await readFile(new URL("../supabase/migrations/202608250007_profile_onboarding_grants.sql", import.meta.url), "utf8"),
  individualPrescriptionMigration: await readFile(new URL("../supabase/migrations/202608250008_individual_exercise_prescriptions.sql", import.meta.url), "utf8"),
  roadmapRealtimeMigration: await readFile(new URL("../supabase/migrations/202608270001_enable_roadmap_realtime.sql", import.meta.url), "utf8"),
  expandedCatalogMigration: await readFile(new URL("../supabase/migrations/202608270002_expand_exercise_catalog.sql", import.meta.url), "utf8"),
  exerciseTrackingMigration: await readFile(new URL("../supabase/migrations/202608270003_exercise_specific_pose_tracking.sql", import.meta.url), "utf8"),
  trackableExerciseMigration: await readFile(new URL("../supabase/migrations/202608270004_add_trackable_exercises.sql", import.meta.url), "utf8"),
  commonExerciseMigration: await readFile(new URL("../supabase/migrations/202608290001_add_common_clinical_exercises.sql", import.meta.url), "utf8"),
  clinicalProgramMigration: await readFile(new URL("../supabase/migrations/202608310001_add_clinical_program_exercises.sql", import.meta.url), "utf8"),
  safetyEventMigration: await readFile(new URL("../supabase/migrations/202608310002_patient_safety_events.sql", import.meta.url), "utf8"),
  rlsIntegrationTest: await readFile(new URL("../supabase/tests/rls_integration.sql", import.meta.url), "utf8"),
  supabaseClient: await readFile(new URL("../src/supabase.js", import.meta.url), "utf8"),
  vercel: await readFile(new URL("../vercel.json", import.meta.url), "utf8"),
};

const requirements = [
  [files.main, "Synthetic product demo", "clearly labeled synthetic demo control"],
  [files.main, "Tracking quality", "tracking-quality UI"],
  [files.main, "BASELINE VS TODAY", "progress comparison"],
  [files.main, "THERAPIST DRILL-DOWN", "longitudinal drill-down"],
  [files.main, "WHY AXION FLAGGED THIS", "explainable flag"],
  [files.main, "No sessions yet", "empty state"],
  [files.main, "Movement Report could not load", "error state"],
  [files.pose, "multiple_people", "multi-person camera state"],
  [files.pose, "permission_denied", "permission camera state"],
  [files.pose, "camera_disconnected", "disconnect camera state"],
  [files.pose, "Starting compatibility mode", "CPU pose-model fallback"],
  [files.pose, "createMovementTracker", "exercise-specific movement tracker"],
  [files.pose, "createRepCycleDetector", "deterministic repetition cycle detector"],
  [files.pose, "profile.minActiveFrames", "profile-specific activation debounce"],
  [files.movementProfiles, "assertMovementProfileCoverage", "complete movement-profile coverage check"],
  [files.movementProfiles, "measureMovementSignal", "exercise-specific signal measurement"],
  [files.css, "prefers-reduced-motion", "reduced-motion support"],
  [files.demo, "70-second automatic pitch", "presenter documentation"],
  [files.main, "Build a treatment roadmap", "therapist plan builder"],
  [files.main, "data-therapist-section", "working therapist workspace tabs"],
  [files.main, "prescription-toggle", "per-exercise dosage controls"],
  [files.main, "data-open-roadmap", "patient roadmap drill-down"],
  [files.main, "patient-roadmap-", "patient-scoped roadmap realtime channel"],
  [files.main, "roadmap-live-state", "roadmap realtime connection state"],
  [files.main, "TREATMENT ROADMAP", "three-biome treatment roadmap"],
  [files.main, "await tracker.start()", "automatic camera tracking start"],
  [files.exerciseCatalog, "heel_to_toe_walk", "expanded exercise library"],
  [files.exerciseCatalog, "sit_to_stand", "functional sit-to-stand exercise"],
  [files.exerciseCatalog, "assisted_shoulder_flexion", "assisted shoulder exercise"],
  [files.exerciseCatalog, "exerciseCategoryOrder", "anatomical exercise sections"],
  [files.exerciseCatalog, "resourceUrl", "trusted exercise guide links"],
  [files.main, "How to do this exercise", "patient exercise instructions"],
  [files.main, "data-library-category", "therapist library category filters"],
  [files.main, "exercise-library-goal", "therapist treatment-goal filter"],
  [files.main, "exercise-library-equipment", "therapist equipment filter"],
  [files.main, "exercise-library-position", "therapist patient-position filter"],
  [files.main, "exercise-library-program", "therapist clinical-program filter"],
  [files.main, "prescription-program", "roadmap-builder clinical-program filter"],
  [files.main, "prescription-common-only", "roadmap-builder commonly-used filter"],
  [files.exerciseCatalog, "exerciseFacets", "consistent clinical exercise facets"],
  [files.exerciseCatalog, "exerciseProgramPresets", "curated clinical program presets"],
  [files.main, "BEFORE YOU MOVE", "movement lab technique panel"],
  [files.main, "data-start-assignment", "patient assignment flow"],
  [files.main, "data-export-report", "movement summary export"],
  [files.main, "data-add-therapist-note", "therapist note workflow"],
  [files.main, "data-replay-mode", "replay and trajectory controls"],
  [files.main, "data-patient-filter", "functional therapist patient filter"],
  [files.main, "Account and identity", "signed-in account workspace"],
  [files.portal, "createTherapistNote", "RLS-backed therapist note persistence"],
  [files.main, "derivedTherapistAlerts", "live descriptive alert generation"],
  [files.portal, "exercise_assignments", "patient prescription data integration"],
  [files.schema, "is_assigned_therapist", "assignment-scoped RLS"],
  [files.portal, "claimCareInvitation", "patient invite claim flow"],
  [files.portal, "createCareInvitation", "therapist invite creation flow"],
  [files.portal, "loadMovementReport", "patient-scoped movement report loader"],
  [files.main, "Create a patient account", "patient onboarding"],
  [files.main, "account-entry-button", "explicit signed-out account action"],
  [files.main, "signup-password-field", "full-width signup password field"],
  [files.main, "safeAuthMessage", "sanitized authentication errors"],
  [files.main, "yourname@example.com", "readable account email fields"],
  [files.css, "password-rules", "responsive password requirement panel"],
  [files.main, "onboarding_version", "one-time onboarding state"],
  [files.main, "resetPasswordForEmail", "secure password recovery request"],
  [files.main, "PASSWORD_RECOVERY", "password recovery callback handling"],
  [files.main, "RECOVERY LINK EXPIRED", "expired recovery link state"],
  [files.main, "window.location.pathname === \"/reset-password\"", "dedicated recovery route detection"],
  [files.vercel, "\"source\": \"/reset-password\"", "password recovery route rewrite"],
  [files.main, "supabase.auth.updateUser({ password })", "authenticated password update"],
  [files.main, "VERIFICATION PENDING", "two-sided connection state"],
  [files.main, "PRIVATE PATIENT LAB", "patient-scoped movement lab"],
  [files.main, "No synthetic values in live records", "live report synthetic-data isolation"],
  [files.main, "data-report-patient-id", "patient-id report routing"],
  [files.main, "feedback.discomfort", "patient reflection persistence"],
  [files.securityMigration, "private.current_app_role", "private authorization helper"],
  [files.securityMigration, "extensions.gen_random_bytes", "cryptographically random invite"],
  [files.securityMigration, "target_email_hash", "email-bound invite"],
  [files.securityMigration, "interval '48 hours'", "48-hour invite expiry"],
  [files.securityMigration, "security_invoker = true", "RLS-respecting status view"],
  [files.pose, "result.worldLandmarks", "3D world-landmark angle measurement"],
  [files.main, "AVG. KNEE BEND", "human-readable knee-bend semantics"],
  [files.main, "average_joint_angle_degrees", "backward-compatible joint-angle summary"],
  [files.main, "average_knee_bend_degrees", "knee-bend summary"],
  [files.personalizationMigration, "one_active_plan_per_patient", "one active patient roadmap"],
  [files.personalizationMigration, "pending_verification", "therapist verification workflow"],
  [files.productionSecurityMigration, "invite_code_hash", "hashed invitation storage"],
  [files.productionSecurityMigration, "publish_patient_plan", "transactional plan publication"],
  [files.individualPrescriptionMigration, "publish_patient_plan_v2", "per-exercise transactional plan publication"],
  [files.individualPrescriptionMigration, "jsonb_array_length(p_exercises) not between 1 and 12", "bounded exercise prescription count"],
  [files.roadmapRealtimeMigration, "supabase_realtime", "roadmap realtime publication"],
  [files.expandedCatalogMigration, "private.exercise_catalog", "private server-authoritative exercise allowlist"],
  [files.expandedCatalogMigration, "revoke all on table private.exercise_catalog", "exercise allowlist access restriction"],
  [files.exerciseTrackingMigration, "tracking_mode = 'pose_reps'", "server-authoritative rep tracking modes"],
  [files.exerciseTrackingMigration, "assignment.status = 'active'", "active-assignment tracking upgrade"],
  [files.trackableExerciseMigration, "marching_in_place", "expanded private trackable exercise allowlist"],
  [files.commonExerciseMigration, "supported_side_stepping", "common clinical exercise allowlist"],
  [files.commonExerciseMigration, "revoke all on table private.exercise_catalog", "common exercise allowlist access restriction"],
  [files.clinicalProgramMigration, "standing_clock_reach", "clinical program exercise allowlist"],
  [files.clinicalProgramMigration, "revoke all on table private.exercise_catalog", "clinical program allowlist access restriction"],
  [files.productionSecurityMigration, "sessions_insert_assigned_patient", "assignment-bound session policy"],
  [files.productionSecurityMigration, "private.audit_events", "private security audit trail"],
  [files.productionSecurityMigration, "client_session_id", "idempotent patient sessions"],
  [files.onboardingGrantMigration, "grant update (display_name, onboarding_version, onboarding_completed_at, updated_at)", "column-scoped onboarding updates"],
  [files.rlsIntegrationTest, "Cross-patient assignment insert was allowed", "cross-patient authorization regression test"],
  [files.rlsIntegrationTest, "Duplicate client session was allowed", "duplicate-session regression test"],
  [files.rlsIntegrationTest, "Per-exercise dosage was not preserved", "per-exercise dosage regression test"],
  [files.rlsIntegrationTest, "Patient could read private therapist notes", "therapist-note privacy regression test"],
  [files.rlsIntegrationTest, "rollback;", "non-persistent security fixtures"],
  [files.supabaseClient, "window.sessionStorage", "session-scoped auth token storage"],
  [files.main, "AUTH_IDLE_TIMEOUT_MS", "authenticated idle-session timeout"],
  [files.main, "Pain or movement concern", "in-session safety pause action"],
  [files.main, "recordPatientSafetyEvent", "immediate patient safety-event persistence"],
  [files.main, "Resume only if you feel ready", "non-coercive safety resume language"],
  [files.portal, "patient_safety_events", "patient safety-event data integration"],
  [files.movementGame, "MOVEMENT_EVENT.SAFETY_FLAG", "safety event overrides game progress"],
  [files.movementGame, "Math.min(clinicalTarget", "game progress capped at prescription"],
  [files.safetyEventMigration, "enable row level security", "safety-event RLS"],
  [files.safetyEventMigration, "patient_safety_events_insert_own_assignment", "assignment-bound safety-event policy"],
  [files.safetyEventMigration, "revoke all on table public.patient_safety_events", "explicit safety-event grants"],
  [files.safetyEventMigration, "private.audit_events", "safety-event audit trail"],
  [files.rlsIntegrationTest, "Patient could alter an append-only safety event", "append-only safety regression test"],
  [files.rlsIntegrationTest, "Cross-patient safety-event insert was allowed", "safety-event IDOR regression test"],
  [files.main, "safeOperationalMessage", "sanitized operational errors"],
  [files.vercel, "Content-Security-Policy", "production content security policy"],
  [files.vercel, "qjcxelpzcfmcsrpsnlrs.supabase.co", "current Supabase CSP origin"],
  [files.vercel, "Permissions-Policy", "camera permissions policy"],
  [files.vercel, "Cross-Origin-Resource-Policy", "cross-origin resource policy"],
  [files.vercel, "private, no-store, max-age=0", "authenticated page cache prevention"],
];

for (const [source, marker, label] of requirements) {
  if (!source.includes(marker)) throw new Error(`Missing ${label}: ${marker}`);
}

const scriptedDurationMs = 7000 + (5 * 8000) + 5000 + 10000 + 8000;
if (scriptedDurationMs !== 70000) throw new Error("Scripted demo must remain 70 seconds.");

const cssBalance = [...files.css].reduce((balance, character) => {
  if (character === "{") return balance + 1;
  if (character === "}") return balance - 1;
  return balance;
}, 0);
if (cssBalance !== 0) throw new Error("Unbalanced CSS braces.");

JSON.parse(files.vercel);
if (files.vercel.includes("kxhmrfgolttrofpumqpy")) throw new Error("CSP still references the retired Supabase project.");
if (!files.vercel.includes("'wasm-unsafe-eval'")) throw new Error("CSP must permit WebAssembly compilation for the MediaPipe pose model.");
if (files.vercel.includes("'unsafe-eval'")) throw new Error("CSP must not permit unrestricted JavaScript eval.");
if (files.main.includes("onclick=")) throw new Error("Inline event handlers are blocked by the production CSP.");
if (/\.textContent\s*=\s*\w*error\.message/i.test(files.main)) {
  throw new Error("Raw database or authentication errors must not be rendered to patients or therapists.");
}

console.log(`Axion smoke test passed: ${requirements.length} feature markers, 70-second script, balanced CSS.`);
