const sources = {
  neck: { label: "NHS neck exercise guide", url: "https://www.nhsinform.scot/illnesses-and-conditions/muscle-bone-and-joints/neck-and-back-problems-and-conditions/exercises-for-neck-problems" },
  shoulder: { label: "NHS shoulder exercise videos", url: "https://www.nhsinform.scot/illnesses-and-conditions/muscle-bone-and-joints/arm-shoulder-and-hand-problems-and-conditions/exercises-for-shoulder-problems" },
  strength: { label: "NHS strength exercise videos", url: "https://www.nhs.uk/live-well/exercise/strength-exercises/" },
  spine: { label: "AAOS spine conditioning guide", url: "https://orthoinfo.aaos.org/en/recovery/spine-conditioning-program/" },
  hip: { label: "AAOS hip conditioning guide", url: "https://orthoinfo.aaos.org/en/recovery/hip-conditioning-program/" },
  knee: { label: "AAOS knee conditioning guide", url: "https://orthoinfo.aaos.org/en/recovery/knee-conditioning-program/" },
  ankle: { label: "AAOS foot and ankle guide", url: "https://orthoinfo.aaos.org/en/recovery/foot-and-ankle-conditioning-program/" },
};

const ex = (name, category, trackingMode, joint, sets, reps, focus, summary, equipment, steps, cues, avoid, source, duration) => ({
  name, category, region: category, trackingMode: trackingMode === "guided_reps" ? "pose_reps" : trackingMode, joint, defaultSets: sets, defaultReps: reps,
  ...(duration ? { defaultDuration: duration } : {}), focus, summary, equipment, steps, cues, avoid,
  safety: "Use only as prescribed. Stop for sharp or increasing pain, dizziness, new numbness, or loss of balance, and contact your care team.",
  resourceLabel: source.label, resourceUrl: source.url,
});

export const exerciseCategoryOrder = [
  "Neck", "Shoulders", "Chest", "Upper back", "Arms & elbows", "Core & abs", "Lower back",
  "Hips & glutes", "Thighs & quads", "Hamstrings", "Knees", "Calves & shins", "Ankles & feet", "Balance",
];

export const exerciseCatalog = {
  chin_tuck: ex("Chin Tuck", "Neck", "guided_reps", "neck", 2, 8, ["Neck control", "Posture", "Comfort"], "Gently trains deep neck control without forcing the head downward.", "Chair or wall (optional)", ["Sit or stand tall with eyes level.", "Glide your chin straight backward, as if making a small double chin.", "Pause briefly, then return without tipping your head."], ["Keep eyes level", "Use a small motion"], "Do not force the chin down or hold your breath.", sources.neck),
  cervical_rotation: ex("Seated Neck Rotation", "Neck", "guided_reps", "neck", 2, 8, ["Rotation", "Control", "Comfort"], "Practices comfortable side-to-side neck motion.", "Supportive chair", ["Sit tall with shoulders relaxed.", "Turn your head slowly toward one side within a comfortable range.", "Return to center and repeat on the other side."], ["Move slowly", "Keep shoulders facing forward"], "Do not push through pinching, dizziness, or arm symptoms.", sources.neck),
  cervical_side_bend: ex("Neck Side Bend", "Neck", "guided_reps", "neck", 2, 8, ["Side bend", "Control", "Comfort"], "Practices gentle side-bending mobility.", "Supportive chair", ["Sit tall and look forward.", "Bring one ear gently toward the same-side shoulder.", "Return to center and alternate sides."], ["Keep nose forward", "Let shoulders stay down"], "Do not lift the shoulder or pull on the head.", sources.neck),
  upper_trap_stretch: ex("Upper Trapezius Stretch", "Neck", "timed_hold", "neck", 2, 1, ["Stretch", "Posture", "Breathing"], "Gently lengthens the side of the neck.", "Supportive chair", ["Sit tall and hold the chair lightly with one hand.", "Tilt the opposite ear toward the opposite shoulder.", "Hold the prescribed time, then switch sides."], ["Breathe normally", "Use gentle tension only"], "Do not yank or rotate the head.", sources.neck, 20),

  shoulder_pendulum: ex("Shoulder Pendulum", "Shoulders", "timed_hold", "shoulder", 2, 1, ["Relaxation", "Shoulder motion", "Control"], "Uses body sway to create gentle shoulder motion.", "Stable table or counter", ["Support yourself with the unaffected arm and lean forward.", "Let the working arm hang completely relaxed.", "Gently sway your body to move the arm in small circles."], ["Let the arm stay loose", "Create motion from body sway"], "Do not actively swing or use a large painful circle.", sources.shoulder, 30),
  wall_crawl: ex("Shoulder Wall Crawl", "Shoulders", "guided_reps", "shoulder", 2, 8, ["Elevation", "Control", "Comfort"], "Uses the fingers to assist comfortable arm elevation.", "Clear wall", ["Face the wall and place fingertips at waist or chest height.", "Walk the fingers upward within the prescribed comfortable range.", "Pause, then walk the fingers slowly down."], ["Keep shoulder relaxed", "Avoid leaning"], "Do not shrug or force beyond the therapist-set range.", sources.shoulder),
  cross_body_shoulder_stretch: ex("Cross-Body Shoulder Stretch", "Shoulders", "timed_hold", "shoulder", 2, 1, ["Posterior shoulder", "Stretch", "Breathing"], "Gently stretches the back of the shoulder.", "None", ["Bring one arm across the front of your chest.", "Support it above the elbow with the other arm.", "Draw it closer until a gentle stretch is felt, then hold."], ["Keep shoulder down", "Breathe normally"], "Do not pull directly on the elbow joint.", sources.shoulder, 30),
  shoulder_external_rotation: ex("Band Shoulder External Rotation", "Shoulders", "guided_reps", "shoulder", 3, 10, ["Rotator cuff", "Control", "Posture"], "Strengthens outward shoulder rotation with the elbow supported at the side.", "Therapist-approved resistance band", ["Anchor the band and stand with the working elbow bent at 90 degrees.", "Keep the elbow gently against your side.", "Rotate the forearm outward slowly, then return with control."], ["Keep wrist neutral", "Do not twist the torso"], "Do not use a resistance level that causes pain or compensation.", sources.shoulder),
  shoulder_internal_rotation: ex("Band Shoulder Internal Rotation", "Shoulders", "guided_reps", "shoulder", 3, 10, ["Rotator cuff", "Control", "Posture"], "Strengthens inward shoulder rotation.", "Therapist-approved resistance band", ["Anchor the band beside you with the elbow bent to 90 degrees.", "Keep the elbow against your side.", "Pull the forearm inward across the abdomen, then return slowly."], ["Stand tall", "Keep elbow still"], "Do not rotate the trunk to finish the motion.", sources.shoulder),
  scapular_retraction: ex("Scapular Retraction", "Shoulders", "guided_reps", "shoulder", 2, 10, ["Shoulder blades", "Posture", "Control"], "Builds controlled shoulder-blade motion.", "Chair (optional)", ["Sit or stand tall with arms relaxed.", "Gently draw the shoulder blades back and slightly down.", "Pause, then release without rounding forward."], ["Keep neck relaxed", "Use a small squeeze"], "Do not shrug or force the chest upward.", sources.shoulder),
  assisted_shoulder_flexion: ex("Assisted Shoulder Flexion", "Shoulders", "guided_reps", "shoulder", 2, 8, ["Shoulder elevation", "Assisted range", "Control"], "Uses the unaffected arm or a light stick to assist forward shoulder elevation.", "Light stick only if prescribed", ["Lie on your back or stand as your therapist instructed and hold a light stick with both hands.", "Use the unaffected arm to guide the working arm upward in front of you.", "Stop at the prescribed comfortable range, then lower slowly."], ["Keep elbows relaxed", "Let the unaffected arm assist"], "Do not force overhead range, shrug, or continue through increasing pain.", sources.shoulder),
  standing_shoulder_abduction: ex("Standing Shoulder Abduction", "Shoulders", "guided_reps", "shoulder", 2, 8, ["Side elevation", "Shoulder control", "Posture"], "Raises the arm out to the side through a therapist-approved range.", "None; light weight only if prescribed", ["Stand tall with the working arm relaxed at your side.", "Raise the arm out to the side with the thumb facing forward.", "Pause in the prescribed range, then lower slowly."], ["Keep shoulder away from ear", "Keep trunk still"], "Do not lean, shrug, or add weight without therapist approval.", sources.shoulder),
  shoulder_scaption: ex("Shoulder Scaption", "Shoulders", "guided_reps", "shoulder", 2, 8, ["Shoulder elevation", "Scapular plane", "Control"], "Raises the arm in the comfortable plane between straight ahead and directly sideways.", "None; light weight only if prescribed", ["Stand tall with the working arm at your side and thumb pointing upward.", "Raise the arm on a gentle diagonal about halfway between forward and sideways.", "Stop at the prescribed height, then lower slowly."], ["Keep thumb up", "Keep shoulder away from ear"], "Do not shrug, lean, or add resistance without therapist approval.", sources.shoulder),
  serratus_wall_slide: ex("Serratus Wall Slide", "Shoulders", "guided_reps", "shoulder", 2, 8, ["Shoulder blade control", "Elevation", "Posture"], "Coordinates upward arm motion with controlled shoulder-blade movement.", "Clear wall and towel (optional)", ["Face a wall with forearms supported and elbows bent.", "Slide both forearms upward while keeping gentle contact with the wall.", "Stop in the prescribed range and return slowly."], ["Keep ribs controlled", "Reach upward without shrugging"], "Do not force overhead range or arch the low back.", sources.shoulder),

  doorway_chest_stretch: ex("Doorway Chest Stretch", "Chest", "timed_hold", "shoulder", 2, 1, ["Chest mobility", "Posture", "Breathing"], "Gently opens the front of the chest and shoulders.", "Doorway", ["Place forearms on the doorway at a therapist-approved height.", "Step forward slightly while keeping the ribs controlled.", "Hold a gentle stretch across the chest."], ["Keep shoulders down", "Breathe normally"], "Do not arch the low back or force shoulder range.", sources.shoulder, 30),
  wall_push_up: ex("Wall Push-Up", "Chest", "guided_reps", "elbow", 2, 10, ["Chest strength", "Arm control", "Alignment"], "A supported push-up that trains chest, shoulders, and arms.", "Clear wall", ["Place hands on the wall at shoulder height and step back.", "Bend the elbows and bring the body toward the wall as one line.", "Press the wall away to return."], ["Keep heels down", "Keep body straight"], "Do not let hips sag or elbows flare excessively.", sources.strength),
  supine_chest_opening: ex("Supine Chest Opening", "Chest", "timed_hold", "shoulder", 2, 1, ["Chest mobility", "Breathing", "Relaxation"], "Uses a supported position to open the chest gently.", "Rolled towel", ["Lie on your back with a rolled towel lengthwise under the upper spine.", "Rest the arms out to the sides at a comfortable angle.", "Breathe slowly and hold only as prescribed."], ["Support the head", "Let ribs relax"], "Do not use if lying flat is uncomfortable or restricted by your clinician.", sources.shoulder, 30),

  thoracic_extension_chair: ex("Thoracic Extension Over Chair", "Upper back", "guided_reps", "spine", 2, 8, ["Upper-back mobility", "Posture", "Breathing"], "Mobilizes the upper back over a supportive chair.", "Firm chair", ["Sit with the chair back supporting the mid-to-upper back.", "Support your head and keep the lower ribs controlled.", "Gently extend over the chair, then return upright."], ["Move through upper back", "Keep motion comfortable"], "Do not force the neck or low back.", sources.spine),
  open_book: ex("Open Book Rotation", "Upper back", "guided_reps", "spine", 2, 8, ["Thoracic rotation", "Breathing", "Control"], "Practices upper-back rotation in side-lying.", "Mat and head support", ["Lie on your side with hips and knees bent and arms together in front.", "Open the top arm across the body while following it with your eyes.", "Return slowly without letting the knees separate."], ["Breathe out as you open", "Keep knees stacked"], "Do not force the shoulder to the floor.", sources.spine),
  seated_row: ex("Band Seated Row", "Upper back", "guided_reps", "shoulder", 3, 10, ["Upper-back strength", "Shoulder blades", "Posture"], "Strengthens the upper back with controlled pulling.", "Therapist-approved resistance band", ["Sit tall with the band anchored safely in front.", "Pull the handles toward the lower ribs while bending the elbows.", "Return slowly until the arms are straight."], ["Squeeze shoulder blades", "Keep trunk still"], "Do not lean backward or shrug.", sources.strength),
  wall_angels: ex("Wall Angels", "Upper back", "guided_reps", "shoulder", 2, 8, ["Posture", "Shoulder mobility", "Control"], "Coordinates shoulder motion with upper-back posture.", "Clear wall", ["Stand with the back comfortably against a wall.", "Place arms in a goalpost position within your available range.", "Slide arms upward and down while maintaining relaxed posture."], ["Keep ribs controlled", "Use a pain-free range"], "Do not force wrists or elbows against the wall.", sources.shoulder),

  biceps_curl: ex("Biceps Curl", "Arms & elbows", "guided_reps", "elbow", 2, 10, ["Elbow strength", "Control", "Tempo"], "Strengthens elbow bending with a controlled load.", "Therapist-approved weights", ["Stand or sit tall with arms at your sides.", "Bend the elbows and bring the weights toward the shoulders.", "Lower slowly until the elbows are straight."], ["Keep elbows near sides", "Keep wrists straight"], "Do not swing the body or use unapproved weight.", sources.strength),
  triceps_extension: ex("Band Triceps Extension", "Arms & elbows", "guided_reps", "elbow", 2, 10, ["Elbow strength", "Control", "Posture"], "Strengthens elbow straightening.", "Therapist-approved resistance band", ["Anchor the band safely and hold it with the elbow bent.", "Keep the upper arm still.", "Straighten the elbow, then return slowly."], ["Keep shoulder relaxed", "Move only the forearm"], "Do not snap or lock the elbow forcefully.", sources.strength),
  wrist_flexor_stretch: ex("Wrist Flexor Stretch", "Arms & elbows", "timed_hold", "wrist", 2, 1, ["Forearm mobility", "Wrist motion", "Comfort"], "Gently stretches the palm-side forearm.", "None", ["Extend one arm with the elbow straight and palm up.", "Use the other hand to guide the fingers gently downward.", "Hold a mild forearm stretch, then release."], ["Keep shoulder down", "Use gentle pressure"], "Do not pull through tingling or sharp wrist pain.", sources.strength, 20),
  forearm_rotation: ex("Forearm Pronation and Supination", "Arms & elbows", "guided_reps", "elbow", 2, 10, ["Forearm rotation", "Elbow control", "Comfort"], "Practices turning the palm up and down.", "Light object only if prescribed", ["Sit with the elbow bent to 90 degrees and held at your side.", "Turn the palm upward slowly.", "Turn the palm downward, keeping the elbow still."], ["Use full comfortable motion", "Move slowly"], "Do not add weight unless the therapist prescribed it.", sources.strength),

  abdominal_bracing: ex("Abdominal Bracing", "Core & abs", "timed_hold", "spine", 3, 1, ["Core control", "Breathing", "Spine position"], "Trains gentle abdominal tension while breathing normally.", "Mat", ["Lie on your back with knees bent and feet supported.", "Gently tighten the lower abdomen as if preparing for a cough.", "Maintain the brace while breathing normally, then relax."], ["Keep pelvis still", "Breathe throughout"], "Do not bear down or flatten the back forcefully.", sources.spine, 10),
  dead_bug: ex("Dead Bug", "Core & abs", "guided_reps", "spine", 2, 8, ["Core control", "Coordination", "Breathing"], "Challenges trunk control while the arms and legs move.", "Mat", ["Lie on your back with hips and knees bent and arms raised.", "Brace gently, then lower the prescribed opposite arm and leg.", "Return to start and alternate sides."], ["Keep ribs down", "Use a short range first"], "Stop if the low back arches or symptoms increase.", sources.spine),
  bridge: ex("Glute Bridge", "Core & abs", "guided_reps", "hip", 3, 10, ["Glutes", "Core control", "Hip extension"], "Strengthens the hips and trunk in a supported position.", "Mat", ["Lie on your back with knees bent and feet hip-width apart.", "Tighten the abdomen and squeeze the glutes.", "Lift the hips to a comfortable line, pause, then lower slowly."], ["Press through both feet", "Keep knees aligned"], "Do not arch beyond a comfortable neutral position.", sources.spine),
  bird_dog: ex("Bird Dog", "Core & abs", "guided_reps", "spine", 2, 8, ["Core control", "Balance", "Coordination"], "Trains trunk stability with opposite arm and leg movement.", "Mat", ["Begin on hands and knees with the spine comfortable.", "Brace gently and reach one arm and the opposite leg away.", "Pause without rotating, return, and switch sides."], ["Keep hips level", "Reach long, not high"], "Do not let the low back sag or twist.", sources.spine),
  modified_front_plank: ex("Modified Front Plank", "Core & abs", "timed_hold", "spine", 3, 1, ["Core endurance", "Shoulder support", "Alignment"], "Builds trunk endurance from forearms and knees.", "Mat", ["Set forearms under shoulders and keep knees on the mat.", "Lift the trunk to form a straight line from head to knees.", "Hold while breathing, then lower with control."], ["Keep neck long", "Gently brace"], "Stop if the shoulders, back, or neck cannot stay comfortable.", sources.spine, 20),
  side_plank_knees: ex("Side Plank From Knees", "Core & abs", "timed_hold", "spine", 2, 1, ["Side core", "Hip support", "Alignment"], "Builds side-trunk endurance in a modified position.", "Mat", ["Lie on one side with knees bent and elbow below the shoulder.", "Lift the hips until the body forms a line from shoulder to knees.", "Hold while breathing, lower, then repeat on the other side."], ["Keep shoulder away from ear", "Keep hips stacked"], "Do not continue if the supporting shoulder is painful.", sources.spine, 15),
  standing_side_bend: ex("Standing Side Bend", "Core & abs", "guided_reps", "spine", 2, 8, ["Side-body mobility", "Trunk control", "Posture"], "Practices small, controlled side bending without rotation.", "None", ["Stand tall with feet supported and arms relaxed.", "Slide one hand a short distance down the same-side thigh while keeping the chest forward.", "Return to center and alternate sides."], ["Keep both feet grounded", "Move directly sideways"], "Do not twist, bounce, or push into pinching pain.", sources.spine),

  pelvic_tilt: ex("Pelvic Tilt", "Lower back", "guided_reps", "spine", 2, 10, ["Lumbar control", "Core awareness", "Breathing"], "Practices small, controlled pelvic motion.", "Mat", ["Lie on your back with knees bent.", "Gently tighten the abdomen and tip the pelvis to reduce the space under the low back.", "Release to the starting position without forcing an arch."], ["Use a small motion", "Breathe normally"], "Do not press through pain.", sources.spine),
  knee_to_chest: ex("Single Knee-to-Chest Stretch", "Lower back", "timed_hold", "hip", 2, 1, ["Low-back mobility", "Hip mobility", "Relaxation"], "Gently brings one hip toward the trunk.", "Mat", ["Lie on your back with knees bent.", "Bring one knee toward the chest and support behind the thigh or over the shin.", "Hold comfortably, lower, and switch sides."], ["Keep other leg relaxed", "Breathe slowly"], "Do not force the knee or lift the head.", sources.spine, 30),
  cat_camel: ex("Cat-Camel", "Lower back", "guided_reps", "spine", 2, 8, ["Spine mobility", "Control", "Breathing"], "Moves the spine gently through comfortable rounding and extension.", "Mat", ["Begin on hands and knees.", "Slowly round the back while letting the head follow.", "Reverse toward a gentle arch, then repeat smoothly."], ["Move one segment at a time", "Stay comfortable"], "Do not force the neck or sink sharply into the low back.", sources.spine),
  seated_trunk_rotation: ex("Seated Trunk Rotation", "Lower back", "guided_reps", "spine", 2, 8, ["Rotation", "Posture", "Control"], "Practices comfortable trunk rotation from a supported seat.", "Firm chair", ["Sit tall with feet supported.", "Cross the arms or rest hands on the chest.", "Turn the trunk gently to one side, return, and alternate."], ["Keep hips facing forward", "Move slowly"], "Do not pull against the chair or force end range.", sources.spine),
  quadruped_rock_back: ex("Quadruped Rock Back", "Lower back", "guided_reps", "spine", 2, 10, ["Hip mobility", "Spine control", "Weight shift"], "Practices a controlled backward hip shift from hands and knees.", "Mat", ["Begin on hands and knees with hands below shoulders and knees below hips.", "Keep the spine comfortable while shifting the hips slowly toward the heels.", "Stop at the prescribed range, then return over the hands."], ["Keep movement smooth", "Let the hips create the motion"], "Do not force the knees, wrists, or low back.", sources.spine),

  clamshell: ex("Clamshell", "Hips & glutes", "guided_reps", "hip", 2, 12, ["Hip rotation", "Glute control", "Pelvic stability"], "Strengthens the side hip while the pelvis stays stacked.", "Mat; band only if prescribed", ["Lie on your side with hips and knees bent and feet together.", "Keep the pelvis stacked and lift the top knee.", "Lower slowly without rolling backward."], ["Keep feet together", "Use a small controlled range"], "Do not rotate the trunk to lift higher.", sources.hip),
  reverse_clamshell: ex("Reverse Clamshell", "Hips & glutes", "guided_reps", "hip", 2, 12, ["Hip rotation", "Control", "Pelvic stability"], "Strengthens inward hip rotation in side-lying.", "Mat", ["Lie on your side with knees bent and together.", "Keep the knees touching and lift the top foot.", "Lower slowly while keeping the pelvis still."], ["Keep knees stacked", "Move from the hip"], "Do not roll the pelvis forward or backward.", sources.hip),
  hip_abduction: ex("Side-Lying Hip Abduction", "Hips & glutes", "guided_reps", "hip", 3, 10, ["Side hip", "Pelvic control", "Alignment"], "Strengthens the outer hip.", "Mat", ["Lie on your side with the bottom knee bent and top leg straight.", "Keep the top leg in line with the trunk and lift it slightly.", "Pause, then lower with control."], ["Point toes forward", "Keep pelvis stacked"], "Do not roll backward or hike the hip.", sources.hip),
  hip_adduction: ex("Side-Lying Hip Adduction", "Hips & glutes", "guided_reps", "hip", 3, 10, ["Inner thigh", "Hip control", "Alignment"], "Strengthens the inner thigh from side-lying.", "Mat", ["Lie on your side and place the top foot in front of the lower leg.", "Keep the lower leg straight and lift it a few inches.", "Pause, then lower slowly."], ["Keep trunk still", "Lead with inner thigh"], "Do not twist the pelvis.", sources.hip),
  prone_hip_extension: ex("Prone Hip Extension", "Hips & glutes", "guided_reps", "hip", 3, 10, ["Glutes", "Hip extension", "Pelvic control"], "Strengthens hip extension while the trunk stays supported.", "Mat and optional pillow", ["Lie on your stomach with the working knee straight.", "Tighten the abdomen and glute.", "Lift the leg slightly without arching the back, then lower."], ["Keep pelvis down", "Lift only a small amount"], "Do not use the low back to create height.", sources.hip),
  standing_hip_flexion: ex("Supported Standing Hip Flexion", "Hips & glutes", "guided_reps", "hip", 2, 10, ["Hip flexion", "Weight shift", "Control"], "Strengthens controlled hip lifting with stable support nearby.", "Stable counter", ["Stand tall beside a stable counter with light hand support.", "Lift the working knee forward without leaning backward.", "Pause at the prescribed height and lower the foot quietly."], ["Keep trunk tall", "Keep pelvis level"], "Do not lift beyond the therapist-set range or practice without support if balance is uncertain.", sources.hip),
  standing_hip_extension: ex("Supported Standing Hip Extension", "Hips & glutes", "guided_reps", "hip", 2, 10, ["Hip extension", "Glute control", "Posture"], "Moves the working leg backward while the trunk stays upright.", "Stable counter", ["Stand tall behind a stable counter with light support.", "Keep the knee straight and move the working leg a short distance backward.", "Pause without arching, then return slowly."], ["Keep toes forward", "Keep trunk still"], "Do not lean forward, arch the back, or swing the leg.", sources.hip),
  figure_four_stretch: ex("Figure-Four Hip Stretch", "Hips & glutes", "timed_hold", "hip", 2, 1, ["Hip mobility", "Glute stretch", "Breathing"], "Gently stretches the back and side of the hip.", "Mat", ["Lie on your back with knees bent.", "Place one ankle across the opposite thigh.", "Draw the supporting thigh toward you until a gentle stretch is felt."], ["Keep head relaxed", "Flex the crossed foot gently"], "Do not press directly on the knee.", sources.hip, 30),

  half_squat: ex("Half Squat", "Thighs & quads", "pose_reps", "knee", 3, 10, ["Quad strength", "Knee control", "Alignment"], "Builds thigh and hip strength through a therapist-set squat range.", "Stable support (optional)", ["Stand with feet about shoulder-width apart.", "Send the hips back and bend the knees to the prescribed depth.", "Press through the feet to stand tall."], ["Track knees over toes", "Keep heels grounded"], "Do not chase depth or let the knees collapse inward.", sources.knee),
  sit_to_stand: ex("Sit-to-Stand", "Thighs & quads", "guided_reps", "knee", 3, 8, ["Functional strength", "Knee control", "Balance"], "Practices the controlled chair-transfer pattern used in daily life.", "Firm, stable chair", ["Sit near the front of a stable chair with feet hip-width apart.", "Lean slightly forward and press through both feet to stand.", "Reach the hips back and lower to the chair with control."], ["Keep knees over toes", "Stand fully before sitting"], "Do not use a rolling chair or drop quickly into the seat.", sources.strength),
  wall_sit: ex("Wall Sit", "Thighs & quads", "timed_hold", "knee", 3, 1, ["Quad endurance", "Knee angle", "Stability"], "Builds thigh endurance in a therapist-selected knee position.", "Clear wall", ["Lean your back against a wall and step the feet forward.", "Slide down to the prescribed comfortable knee angle.", "Hold with knees aligned, then slide up."], ["Keep pressure even", "Breathe normally"], "Do not hold lower or longer than prescribed.", sources.knee, 30),
  leg_extension: ex("Seated Leg Extension", "Thighs & quads", "guided_reps", "knee", 3, 10, ["Quad strength", "Knee motion", "Control"], "Strengthens knee extension from a supported seat.", "Firm chair; ankle weight only if prescribed", ["Sit tall with the thigh supported.", "Straighten the knee to the prescribed range.", "Pause, then lower slowly."], ["Keep thigh on chair", "Control the lowering"], "Do not kick quickly or add unapproved weight.", sources.knee),
  straight_leg_raise: ex("Straight-Leg Raise", "Thighs & quads", "guided_reps", "hip", 3, 10, ["Quad control", "Hip strength", "Knee position"], "Builds quadriceps control while the knee remains straight.", "Mat", ["Lie on your back with one knee bent and the working leg straight.", "Tighten the working thigh so the knee stays straight.", "Lift to about the height of the opposite knee, then lower slowly."], ["Set the quad first", "Keep toes upward"], "Stop if the knee bends or the back strains.", sources.knee),
  standing_quad_stretch: ex("Standing Quadriceps Stretch", "Thighs & quads", "timed_hold", "knee", 2, 1, ["Quad mobility", "Balance", "Posture"], "Gently stretches the front of the thigh.", "Stable support", ["Hold a stable surface and bend one knee.", "Hold the ankle or use a strap as instructed.", "Bring the heel gently toward the buttock while keeping knees close."], ["Stand tall", "Keep knees together"], "Do not pull hard or arch the low back.", sources.knee, 30),

  hamstring_curl: ex("Standing Hamstring Curl", "Hamstrings", "guided_reps", "knee", 3, 10, ["Hamstring strength", "Knee control", "Balance"], "Strengthens knee bending while standing with support.", "Stable chair or counter", ["Stand tall while holding a stable support.", "Bend one knee and bring the heel toward the buttock.", "Pause, then lower slowly without moving the hip."], ["Keep thighs aligned", "Stand tall"], "Do not swing the leg or arch the back.", sources.knee),
  supine_hamstring_stretch: ex("Supine Hamstring Stretch", "Hamstrings", "timed_hold", "hip", 2, 1, ["Hamstring mobility", "Hip position", "Breathing"], "Gently stretches the back of the thigh with the trunk supported.", "Mat and strap (optional)", ["Lie on your back and lift one thigh toward you.", "Support behind the thigh or use a strap.", "Gently straighten the knee until a mild stretch is felt."], ["Keep hips level", "Relax the shoulders"], "Do not force the knee straight or pull behind the knee joint.", sources.knee, 30),
  seated_hamstring_stretch: ex("Seated Hamstring Stretch", "Hamstrings", "timed_hold", "hip", 2, 1, ["Hamstring mobility", "Posture", "Breathing"], "Stretches the back of the thigh from sitting.", "Firm chair", ["Sit near the edge with one leg straight and heel down.", "Keep the back long and hinge forward from the hips.", "Stop when a gentle stretch is felt behind the thigh."], ["Point toes upward", "Keep chest lifted"], "Do not round aggressively or bounce.", sources.knee, 30),

  bodyweight_squat: ex("Bodyweight Squat", "Knees", "pose_reps", "knee", 3, 10, ["Knee bend", "Tempo", "Symmetry"], "Trains a controlled sit-and-stand pattern with live knee-angle feedback.", "Stable chair behind you (optional)", ["Stand with feet about shoulder-width apart and full body visible to the camera.", "Send hips back and bend the knees to the therapist-set depth.", "Press evenly through both feet to stand tall."], ["Knees track over toes", "Keep heels down", "Move at a steady tempo"], "Do not rush, collapse the knees inward, or push deeper for points.", sources.knee),
  forward_lunge: ex("Supported Forward Lunge", "Knees", "guided_reps", "knee", 2, 8, ["Knee control", "Hip strength", "Balance"], "Trains a controlled split-stance lowering pattern with stable support nearby.", "Stable rail or counter", ["Stand beside stable support and step one foot forward.", "Lower the back knee toward the floor while both feet point forward.", "Press through the front foot to return, then repeat the prescribed side."], ["Keep front knee aligned", "Keep trunk tall"], "Do not use an unstable stance or allow the front knee to twist inward.", sources.knee),
  step_up: ex("Step-Up", "Knees", "guided_reps", "knee", 3, 10, ["Knee control", "Leg strength", "Balance"], "Builds controlled stair-like strength.", "Therapist-approved step and rail", ["Place the whole working foot on the step.", "Lean slightly forward and press through that foot to step up.", "Lower with control and repeat the prescribed side."], ["Keep knee aligned", "Use rail only as needed"], "Do not use an unstable or unapproved step height.", sources.knee),
  lateral_step_up: ex("Lateral Step-Up", "Knees", "guided_reps", "knee", 2, 8, ["Side-step control", "Hip strength", "Knee alignment"], "Builds controlled side stepping on a therapist-approved step.", "Therapist-approved low step and rail", ["Stand beside the step and place the whole working foot on it.", "Press through the working foot to bring the body onto the step.", "Lower slowly to the same side and repeat as prescribed."], ["Keep knee over foot", "Keep pelvis level"], "Do not use an unstable step or practice without the prescribed support.", sources.knee),
  standing_hip_abduction: ex("Standing Hip Abduction", "Hips & glutes", "guided_reps", "hip", 2, 10, ["Side hip", "Pelvic control", "Balance"], "Strengthens the outer hip while standing with support.", "Stable chair or counter", ["Stand tall beside a stable support.", "Keep the working knee straight and move the leg slightly out to the side.", "Return slowly without letting the foot swing across the body."], ["Keep toes forward", "Keep pelvis level"], "Do not lean the trunk or lift the leg high enough to lose balance.", sources.hip),
  terminal_knee_extension: ex("Band Terminal Knee Extension", "Knees", "guided_reps", "knee", 3, 10, ["Knee extension", "Quad control", "Alignment"], "Strengthens the final portion of knee straightening.", "Therapist-approved band and anchor", ["Loop the band behind the working knee with slight tension.", "Begin with the knee softly bent.", "Tighten the thigh and straighten the knee, then return slowly."], ["Keep heel down", "Move the knee, not the trunk"], "Do not lock the knee forcefully.", sources.knee),
  heel_slide: ex("Heel Slide", "Knees", "guided_reps", "knee", 2, 10, ["Knee mobility", "Control", "Comfort"], "Practices bending and straightening the knee with support.", "Mat; strap or towel optional", ["Lie on your back with both legs relaxed.", "Slide one heel toward the buttock to bend the knee.", "Pause in the prescribed range, then slide the leg straight."], ["Keep heel in contact", "Move smoothly"], "Do not force beyond the therapist-set range.", sources.knee),

  heel_raise: ex("Calf Raise", "Calves & shins", "guided_reps", "ankle", 2, 10, ["Calf strength", "Ankle control", "Balance"], "Strengthens the calf by lifting the heels.", "Stable chair or counter", ["Stand tall with feet hip-width apart and light hand support.", "Rise onto the balls of both feet.", "Pause, then lower the heels slowly."], ["Lift straight up", "Keep weight even"], "Do not roll onto the outer feet or bounce.", sources.ankle),
  seated_calf_raise: ex("Seated Calf Raise", "Calves & shins", "guided_reps", "ankle", 2, 12, ["Calf strength", "Ankle control", "Supported posture"], "Trains heel lifting from a stable seated position.", "Firm chair", ["Sit tall with both feet flat and knees bent.", "Keep the toes down and lift both heels.", "Pause, then lower the heels slowly."], ["Keep pressure through the forefeet", "Lift evenly"], "Do not add weight over the knees unless your therapist prescribed it.", sources.ankle),
  heel_cord_stretch: ex("Straight-Knee Calf Stretch", "Calves & shins", "timed_hold", "ankle", 2, 1, ["Calf mobility", "Ankle position", "Alignment"], "Stretches the upper calf with the back knee straight.", "Clear wall", ["Face a wall with one leg behind you.", "Keep the back knee straight and heel down.", "Lean forward until a gentle calf stretch is felt."], ["Point toes forward", "Keep heel grounded"], "Do not bounce or turn the foot outward.", sources.ankle, 30),
  bent_knee_heel_cord_stretch: ex("Bent-Knee Calf Stretch", "Calves & shins", "timed_hold", "ankle", 2, 1, ["Deep calf mobility", "Ankle position", "Control"], "Stretches the deeper calf with the back knee slightly bent.", "Clear wall", ["Face a wall with one foot behind you.", "Keep the back heel down and bend both knees slightly.", "Shift forward until a gentle lower-calf stretch is felt."], ["Keep arch supported", "Keep heel down"], "Do not let the ankle collapse inward.", sources.ankle, 30),
  tibialis_raise: ex("Tibialis Raise", "Calves & shins", "guided_reps", "ankle", 2, 12, ["Shin strength", "Ankle control", "Balance"], "Strengthens the muscles that lift the front of the foot.", "Wall or stable support", ["Stand with the back supported and heels on the floor.", "Lift the toes and forefeet toward the shins.", "Pause, then lower slowly."], ["Keep heels down", "Lift both feet evenly"], "Do not rock backward or lose balance.", sources.ankle),

  ankle_dorsiflexion: ex("Band Ankle Dorsiflexion", "Ankles & feet", "guided_reps", "ankle", 3, 10, ["Ankle strength", "Control", "Range"], "Strengthens lifting the foot toward the shin.", "Therapist-approved band", ["Sit with the band anchored in front and looped over the forefoot.", "Pull the toes toward the shin against the band.", "Return slowly without turning the foot."], ["Keep heel still", "Move straight upward"], "Do not use a band setup that can slip.", sources.ankle),
  ankle_pumps: ex("Ankle Pumps", "Ankles & feet", "guided_reps", "ankle", 2, 10, ["Ankle mobility", "Calf motion", "Control"], "Moves the ankle smoothly between toes-up and toes-away positions.", "Chair or mat", ["Sit or lie with the leg supported as prescribed.", "Pull the toes toward the shin.", "Point the foot away, then continue through a smooth comfortable cycle."], ["Keep the knee still", "Move only at the ankle"], "Do not force either end of the range or move through increasing pain.", sources.spine),
  ankle_plantar_flexion: ex("Band Ankle Plantar Flexion", "Ankles & feet", "guided_reps", "ankle", 3, 10, ["Ankle strength", "Calf control", "Range"], "Strengthens pointing the foot away from the body.", "Therapist-approved band", ["Sit with the leg supported and band around the forefoot.", "Point the foot away against the band.", "Return slowly to neutral."], ["Keep knee still", "Move through the ankle"], "Do not snap the band or curl the toes to substitute.", sources.ankle),
  ankle_range_of_motion: ex("Ankle Alphabet", "Ankles & feet", "guided_reps", "ankle", 1, 1, ["Ankle mobility", "Control", "Range"], "Moves the ankle through multiple directions using small letter shapes.", "Chair", ["Sit with the foot unsupported.", "Use the big toe as a pointer to trace the alphabet in the air.", "Keep the leg still and make the letters from the ankle."], ["Use smooth motions", "Keep letters small"], "Do not force painful directions.", sources.ankle),
  towel_curl: ex("Towel Curl", "Ankles & feet", "guided_reps", "ankle", 2, 10, ["Foot strength", "Toe control", "Arch support"], "Strengthens the small muscles of the foot.", "Chair and small towel", ["Sit with the foot flat on a towel.", "Curl the toes to gather the towel toward you.", "Relax the toes, reset the towel, and repeat."], ["Keep heel down", "Use the toes, not the whole leg"], "Stop if the toes cramp repeatedly.", sources.ankle),
  toe_yoga: ex("Toe Yoga", "Ankles & feet", "guided_reps", "ankle", 2, 10, ["Toe control", "Arch support", "Coordination"], "Practices independent big-toe and lesser-toe control.", "Chair", ["Sit with the whole foot supported.", "Keep the big toe down while lifting the other toes.", "Then lift the big toe while keeping the other toes down."], ["Keep heel planted", "Use slow attempts"], "Do not grip the floor or force stiff toes.", sources.ankle),

  single_leg_balance: ex("Single-Leg Balance", "Balance", "timed_hold", "knee", 3, 1, ["Balance", "Sway", "Control"], "Builds supported single-leg stability.", "Stable counter and clear area", ["Stand beside a stable support.", "Shift weight to one leg and lift the other foot slightly.", "Hold with level hips, then lower and switch as prescribed."], ["Keep a fingertip near support", "Look at a fixed point"], "Do not practice without nearby support or if your therapist has not cleared it.", sources.strength, 30),
  marching_in_place: ex("Supported Marching in Place", "Balance", "guided_reps", "hip", 2, 10, ["Hip flexion", "Weight shift", "Coordination"], "Practices alternating weight shift and foot clearance with support nearby.", "Stable counter", ["Stand tall behind a stable counter with light hand support.", "Lift one knee toward the prescribed height without leaning.", "Lower the foot, then alternate sides at a controlled pace."], ["Keep trunk tall", "Place each foot quietly"], "Do not march without support if balance is uncertain.", sources.strength),
  seated_march: ex("Seated March", "Balance", "guided_reps", "hip", 2, 10, ["Hip flexion", "Coordination", "Seated control"], "Practices alternating hip lifting from a supported chair.", "Firm chair", ["Sit tall near the front of a firm chair with both feet supported.", "Lift one knee a short distance without leaning backward.", "Lower quietly and alternate sides."], ["Keep trunk tall", "Keep each knee facing forward"], "Do not use a rolling chair or continue if you feel unsteady.", sources.strength),
  tandem_stance: ex("Tandem Stance", "Balance", "timed_hold", "ankle", 3, 1, ["Narrow-base balance", "Posture", "Control"], "Challenges balance with one foot directly in front of the other.", "Stable counter and clear area", ["Stand beside a stable support.", "Place one foot directly in front of the other, heel to toe.", "Hold upright, then switch which foot is forward."], ["Look forward", "Use support as needed"], "Do not continue if you feel unsafe or dizzy.", sources.strength, 30),
  heel_to_toe_walk: ex("Heel-to-Toe Walk", "Balance", "guided_reps", "ankle", 2, 10, ["Walking balance", "Coordination", "Control"], "Practices a narrow, controlled walking line.", "Counter or hallway rail", ["Stand beside a stable support.", "Place one foot directly in front of the other so heel meets toes.", "Take slow steps along the line while looking forward."], ["Move slowly", "Use support before balance is lost"], "Do not perform near obstacles or without therapist clearance.", sources.strength),
};

export const exerciseCatalogSource = {
  name: "AAOS OrthoInfo and NHS clinician-reviewed exercise guidance",
  url: "https://orthoinfo.aaos.org/en/recovery/",
  note: "Educational guidance only. A licensed therapist must select suitability, dosage, precautions, and progression.",
};
